server:
  port: 80
spring:
  application:
    name: cloudserverorderconsumer
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/biye?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    druid:
      password: 123456
      username: root

eureka:
  client:
    #需要注册到注册中心
    register-with-eureka: true
    #需要检索服务
    fetch-registry: true
    service-url:
      #默认访问端点
      #defaultZone: http://localhost:7001/eureka  #单机版本
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #集群版本
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
feign:
  client:
    config:
      default:
        connect-timeout: 60000
        read-timeout: 60000